remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gems:
  - jekyll-seo-tag

  title: Kumala Web Development
  tagline: Quality work at a discounted price
  description: Kumala works to provide beautifully efficient websites at a fraction of market price. We are a team dedicated to providing our clients with professional custom websites.
  url: https://danieleyny.github.io/Kumala/
  author: Daniel Eyny
  social:
  name: Daniel Eyny
  links:
  - https://www.linkedin.com/in/daniel-eyny
  - https://www.instagram.com/danieleyny/?hl=en
  - https://www.facebook.com/daniel.eyny
  - https://github.com/danieleyny